# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sharemypaper

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4ff102e14f2c444a840a97b462ee1486 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_596eaf5cbf184ef4be18acd4e1d86c5d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4ff102e14f2c444a840a97b462ee1486 }}/sharemypaper:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sharemypaper'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e5d6d7009a5746c59e7e8526dc849802 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4ff102e14f2c444a840a97b462ee1486 }}/sharemypaper:${{ github.sha }}'
